#创建用户表
CREATE TABLE IF NOT EXISTS `user`  (
  `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(30)  ,
  `email` VARCHAR(50)  NOT NULL UNIQUE,
  `cid` VARCHAR(20)  NOT NULL UNIQUE,
  `password` VARCHAR(50)  NOT NULL,
  `aratar_url` VARCHAR(200) ,
  `signature` VARCHAR(200) ,
  `state` INT DEFAULT 0,
  `createAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updateAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

# 创建注册表register
CREATE TABLE IF NOT EXISTS `register` (
   `id` INT PRIMARY KEY AUTO_INCREMENT, 
   `email` VARCHAR(50)  NOT NULL ,
   `code` VARCHAR(30) NOT NULL, 
   `end_time` TIMESTAMP NOT NULL, 
   `createAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  ); 
#创建号码表cid
CREATE TABLE IF NOT EXISTS `cid` (
   `id` INT PRIMARY KEY AUTO_INCREMENT, 
   `cid` VARCHAR(20)  NOT NULL ,
   `state` INT DEFAULT 0 , 
   `createAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   `updateAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  );